
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.parser.JSONParser;
import org.json.JSONArray;
import org.json.JSONObject;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vitorassis
 */
public class main extends javax.swing.JFrame {

    private String arq = "../configs.json";
    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        
        
        String result = "";
        try {
            BufferedReader br = new BufferedReader(new FileReader(arq));
            StringBuilder sb = new StringBuilder();
            String line = br.readLine();
            while (line != null) {
                sb.append(line);
                line = br.readLine();
            }
            result = sb.toString();
            
            String jsonData = result;
            JSONObject jobj = new JSONObject(jsonData);
            
            cbxProj.setSelected(jobj.getBoolean("projetor"));
            cbxArcos.setSelected(jobj.getBoolean("arcos"));
            cbxHoras.setSelected(jobj.getBoolean("horas redondas"));
        } catch(Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbxArcos = new javax.swing.JCheckBox();
        cbxHoras = new javax.swing.JCheckBox();
        cbxProj = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Configurações - Relógio");

        cbxArcos.setText("Mostrar Arcos");
        cbxArcos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxArcosActionPerformed(evt);
            }
        });

        cbxHoras.setText("Horas Redondas");
        cbxHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxHorasActionPerformed(evt);
            }
        });

        cbxProj.setText("Exibição em Projetor");
        cbxProj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProjActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxProj)
                    .addComponent(cbxHoras)
                    .addComponent(cbxArcos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(76, 76, 76)
                .addComponent(cbxArcos)
                .addGap(18, 18, 18)
                .addComponent(cbxHoras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxProj)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void salvar(){
        JSONObject my_obj = new JSONObject();
 
        //preenche o objeto
        my_obj.put("projetor", cbxProj.isSelected());
        my_obj.put("arcos", cbxArcos.isSelected());
        my_obj.put("horas redondas", cbxHoras.isSelected());
        
        String txt = my_obj.toString();
                
        File file = new File(arq);
        String s = txt;
          try{
            // Create file 
            FileWriter fstream = new FileWriter(file,false);
            BufferedWriter out = new BufferedWriter(fstream);
            out.write(s);
            //Close the output stream
            out.close();
        }
        catch (IOException e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
         
    }
    
    private void cbxArcosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxArcosActionPerformed
        salvar();
    }//GEN-LAST:event_cbxArcosActionPerformed

    private void cbxHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxHorasActionPerformed
        salvar();
    }//GEN-LAST:event_cbxHorasActionPerformed

    private void cbxProjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProjActionPerformed
        salvar();
    }//GEN-LAST:event_cbxProjActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbxArcos;
    private javax.swing.JCheckBox cbxHoras;
    private javax.swing.JCheckBox cbxProj;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
